[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo-extended --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
